(ns project-euler.p44
)


;Pentagon numbers
;Problem 44
;Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

;1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

;It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

;Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk  Pj| is minimised; what is the value of D?


; n(3n-1)/2 + m(3m-1)/2 = r(3r-1)/2
; n(3n-1)/2 - m(3m-1)/2 = s(3s-1)/2

; 2 * n(3n-1)/2 = r(3r-1)/2 + s(3s-1)/2

; x(3x-1)/2 = y
; 3x^2 - x - 2y = 0

(defn pent [n]
  (* n (dec (* 3 n)) 1/2 ))


(time
 (println
   (let [rt (range 1 10001)
         pt (set (map pent rt))]
   (for [n (range 1 5001)
         m (range 1 n)
         :when (not (nil? (pt  (+ (pent n) (pent m)))))
         :when (not (nil? (pt  (- (pent n) (pent m)))))
         ]
     [m n]
     ))

  ))
;[1020 2167]

(- (pent 2167) (pent 1020))
;5482660