(ns project-euler.p45
)



;Triangular, pentagonal, and hexagonal
;Problem 45
;Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

;Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
;Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
;Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
;It can be verified that T285 = P165 = H143 = 40755.

;Find the next triangle number that is also pentagonal and hexagonal.



(defn tr [n]
  (* n (inc n) 1/2))

(defn pent [n]
  (* n (dec (* 3 n)) 1/2 ))


(defn hexa [n]
  (* n (dec (* 2 n))))

(time
  (println
  (let [r (range 1 100000)
        t1 (set (map tr r))
        p1 (set (map pent r))
        h1 (set (map hexa r))
        ]
    (clojure.set/intersection t1 p1 h1))))
;#{1 1533776805 40755}
